#! /bin/bash

proc_name=$1
pid=$2

pid_dir=~/.pid
mkdir ${pid_dir} 2>/dev/null
echo "${pid}" > ${pid_dir}/${proc_name}.pid
echo "check process ${proc_name} with pidfile ${pid_dir}/${proc_name}.pid" >> ~/.monitrc
monit reload
